INSERT INTO permission (permission_id, name, resource)
SELECT * FROM (
                  SELECT gen_random_uuid()::VARCHAR as permission_id, 'ORDER_VIEW' as name, 'Order' as resource
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'ORDER_CREATE', 'Order'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'ORDER_UPDATE', 'Order'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'ORDER_DELETE', 'Order'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'ORDER_CANCEL', 'Order'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'DISH_VIEW', 'Dish'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'DISH_CREATE', 'Dish'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'DISH_EDIT', 'Dish'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'DISH_DELETE', 'Dish'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'CATEGORY_CREATE', 'Category'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'CATEGORY_UPDATE', 'Category'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'CATEGORY_DELETE', 'Category'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'CATEGORY_VIEW', 'Category'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'TABLE_VIEW', 'DiningTable'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'TABLE_CREATE', 'DiningTable'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'TABLE_EDIT', 'DiningTable'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'TABLE_DELETE', 'DiningTable'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'REPORT_VIEW', 'Report'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'REPORT_EXPORT', 'Report'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'USER_VIEW', 'User'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'USER_CREATE', 'User'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'USER_EDIT', 'User'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'USER_DELETE', 'User'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'ROLE_VIEW', 'Role'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'ROLE_CREATE', 'Role'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'ROLE_EDIT', 'Role'
    UNION ALL SELECT gen_random_uuid()::VARCHAR, 'ROLE_DELETE', 'Role'
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM permission);